% prompt = {'Hessian','Enter colormap name:'};
% dlg_title = 'Input';
% num_lines = 1;
% defaultans = {'20','hsv'};
% answer = inputdlg(prompt,dlg_title,num_lines,defaultans);

function flag = chooseopt

    d = dialog('Position',[300 300 300 400],'Name','Select type of optimisation process');

    txtPenalty = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[0 260 300 20],...
           'String','Include Penalty Parameter?');
       
    popupPenalty = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[50 240 200 20],...
           'String',{'No';'Yes'},...
           'Callback',@penalty_callback);
    
    txtHessian = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[0 200 300 20],...
           'String','Select a Hessian Update Method');
       
    popupHessian = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[50 180 200 20],...
           'String',{'Forward Differencing';'Central Differencing';'BFGS'},...
           'Callback',@hessian_callback);
       
   txtLineSearch = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[0 140 300 20],...
           'String','Select a Line Search Method');  
       
    popupLineSearch = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[50 120 200 20],...
           'String',{'alphamax';'Wolfe Conditions';'Backtracking'},...
           'Callback',@Linefn_callback); 
       
    txtMerit = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[0 80 300 20],...
           'String','Include Merit function?');  
       
    popupMerit = uicontrol('Parent',d,...
           'Style','popup',...
           'Position',[50 60 200 20],...    % from left, from bottom,length, width(height)
           'String',{'No';'Yes'},...
           'Callback',@merit_callback);   
       
    btn = uicontrol('Parent',d,...
           'Position',[89 20 70 25],...
           'String','Accept',...
           'Callback','delete(gcf)');
       
        % Set defaults?
    flag.hessian = 'Forward Differencing';
    flag.linefn = 'alphamax';
    flag.merit = 'No';
    flag.penalty = 'No';
       
    % Wait for d to close before running to completion
    uiwait(d);
     function hessian_callback(popup,callback)
          idx = popup.Value;
          popup_items = popup.String;
          flag.hessian = char(popup_items(idx,:));
     end
 
     function Linefn_callback(popup,callback)
          idx = popup.Value;
          popup_items = popup.String;
          flag.linefn = char(popup_items(idx,:));
     end
 
     function merit_callback(popup,callback)
          idx = popup.Value;
          popup_items = popup.String;
          flag.merit = char(popup_items(idx,:));
     end
 
     function penalty_callback(popup,callback)
          idx = popup.Value;
          popup_items = popup.String;
          flag.penalty = char(popup_items(idx,:));
     end

end


